### ISSUE TITLE
Vue warn: Invalid prop: type check failed for prop "root". Expected Object, got HTMLDivElement 

### ISSUE THREAD

**Issue by narek-dev** [BiYuqi/vue-intersection-observer#26]
Guys in docs is writed, what root is HTMLElement, but in real there is just a Object, and when we passing HTMLElement we get an error...
**The docs.**
![image](https://user-images.githubusercontent.com/87359867/157410231-8dd08376-3480-48cd-88b4-fd3c27046ef4.png)
**The native code**
![image](https://user-images.githubusercontent.com/87359867/157410756-936757b0-f1e4-4396-a432-e05909fd249d.png)
**The error**
![image](https://user-images.githubusercontent.com/87359867/157410866-4abf090c-a9bb-4ee3-a463-a0dfd566b145.png)

**Comment by BiYuqi** [comment]
@narek-dev Fixed, thanks for the reminder!
